# Generated by Django 4.2.26 on 2025-11-29 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VillaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ALLImages')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
